### ISSUE TITLE
isinf isnan functions without standard namespace def

### ISSUE THREAD

**Issue by privatereese** [argos-research/speed-dreams#6]
The functions isnan() isinf() do not come with std:: definition.
This leads to build errors under ubuntu 16.04 please fix and edit

isnan()
isinf()

**Comment by irgendwie** [comment]
Already fixed on the KIA4SM branch:
https://github.com/702nADOS/speed-dreams/commit/5ee2215771870f965571e91b0940f4ee36f1db93

**Comment by privatereese** [comment]
should this also be fixed in the master branch as we have agreed on using ubuntu 16.04 and this is a main issue with the chosen OS?

**Comment by irgendwie** [comment]
Cherry-Pick if you'd like, but the branch will be merged in near future
